language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t fred921/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fred921/docker-react npm run test
