language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t fred921/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fred921/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  bucket_name: "elasticbeanstalk-eu-north-1-829823162674"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
